package aoc
package y2020

@main def run(): Unit =
  println("y2020:")
  println("  day1:")
  println(s"    ├ solution #1: ${timed(Day1.solve(Day1.input))}")
  println(s"    └ solution #2: ${timed(Day1.solve2(Day1.input))}")
  println("  day2:")
  println(s"    ├ solution #1: ${timed(Day2.solve(Day2.input))}")
  println(s"    └ solution #2: ${timed(Day2.solve2(Day2.input))}")
  println("  day3:")
  println(s"    ├ solution #1: ${timed(Day3.solve(Day3.input))}")
  println(s"    └ solution #2: ${timed(Day3.solve2(Day3.input))}")
  println("  day4:")
  println(s"    ├ solution #1: ${timed(Day4.solve(Day4.input))}")
  println(s"    └ solution #2: ${timed(Day4.solve2(Day4.input))}")
  println("  day5:")
  println(s"    ├ solution #1: ${timed(Day5.solve(Day5.input))}")
  println(s"    └ solution #2: ${timed(Day5.solve2(Day5.input))}")
  println("  day6:")
  println(s"    ├ solution #1: ${timed(Day6.solve(Day6.input))}")
  println(s"    └ solution #2: ${timed(Day6.solve2(Day6.input))}")
  println("  day7:")
  println(s"    ├ solution #1: ${timed(Day7.solve(Day7.input))}")
  println(s"    └ solution #2: ${timed(Day7.solve2(Day7.input))}")
  println("  day8:")
  println(s"    ├ solution #1: ${timed(Day8.solve(Day8.input))}")
  println(s"    └ solution #2: ${timed(Day8.solve2(Day8.input))}")
  println("  day9:")
  println(s"    ├ solution #1: ${timed(Day9.solve(Day9.input))}")
  println(s"    └ solution #2: ${timed(Day9.solve2(Day9.input))}")
  println("  day10:")
  println(s"    ├ solution #1: ${timed(Day10.solve(Day10.input))}")
  println(s"    └ solution #2: ${timed(Day10.solve2(Day10.input))}")
  println("  day11:")
  println(s"    ├ solution #1: ${timed(Day11.solve(Day11.input))}")
  println(s"    └ solution #2: ${timed(Day11.solve2(Day11.input))}")
  println("  day12:")
  println(s"    ├ solution #1: ${timed(Day12.solve(Day12.input))}")
  println(s"    └ solution #2: ${timed(Day12.solve2(Day12.input))}")
  println("  day13:")
  println(s"    ├ solution #1: ${timed(Day13.solve(Day13.input))}")
  println(s"    └ solution #2: ${timed(Day13.solve2(Day13.input))}")
  println("  day14:")
  println(s"    ├ solution #1: ${timed(Day14.solve(Day14.input))}")
  println(s"    └ solution #2: ${timed(Day14.solve2(Day14.input))}")
  println("  day15:")
  println(s"    ├ solution #1: ${timed(Day15.solve(Day15.input))}")
  println(s"    └ solution #2: ${timed(Day15.solve2(Day15.input))}")
  println("  day16:")
  println(s"    ├ solution #1: ${timed(Day16.solve(Day16.input))}")
  println(s"    └ solution #2: ${timed(Day16.solve2(Day16.input))}")
  println("  day17:")
  println(s"    ├ solution #1: ${timed(Day17.solve(Day17.input))}")
  println(s"    └ solution #2: ${timed(Day17.solve2(Day17.input))}")
  println("  day18:")
  println(s"    ├ solution #1: ${timed(Day18.solve(Day18.input))}")
  println(s"    └ solution #2: ${timed(Day18.solve2(Day18.input))}")
  println("  day19:")
  println(s"    ├ solution #1: ${timed(Day19.solve(Day19.input))}")
  println(s"    └ solution #2: ${timed(Day19.solve2(Day19.input))}")
  println("  day20:")
  println(s"    ├ solution #1: ${timed(Day20.solve(Day20.input))}")
  println(s"    └ solution #2: ${timed(Day20.solve2(Day20.input))}")
  println("  day21:")
  println(s"    ├ solution #1: ${timed(Day21.solve(Day21.input))}")
  println(s"    └ solution #2: ${timed(Day21.solve2(Day21.input))}")
  println("  day22:")
  println(s"    ├ solution #1: ${timed(Day22.solve(Day22.input))}")
  println(s"    └ solution #2: ${timed(Day22.solve2(Day22.input))}")
  // println("  day23:")
  // println(s"    ├ solution #1: ${timed(Day23.solve(Day23.input))}")
  // println(s"    └ solution #2: ${timed(Day23.solve2(Day23.input))}")
  println("  day24:")
  println(s"    ├ solution #1: ${timed(Day24.solve(Day24.input))}")
  println(s"    └ solution #2: ${timed(Day24.solve2(Day24.input))}")
  println("  day25:")
  // println(s"    ├ solution #1: ${timed(Day25.solve(Day25.input))}")
