package aoc
package y2025

@main def run(): Unit =
  println("y2025:")
  println("  day1:")
  println(s"    ├ solution #1: ${timed(Day1.solve(Day1.input))}")
  println(s"    └ solution #2: ${timed(Day1.solve2(Day1.input))}")
  println("  day2:")
  println(s"    ├ solution #1: ${timed(Day2.solve(Day2.input))}")
  println(s"    └ solution #2: ${timed(Day2.solve2(Day2.input))}")
  println("  day3:")
  println(s"    ├ solution #1: ${timed(Day3.solve(Day3.input))}")
  println(s"    └ solution #2: ${timed(Day3.solve2(Day3.input))}")
  println("  day4:")
  println(s"    ├ solution #1: ${timed(Day4.solve(Day4.input))}")
  println(s"    └ solution #2: ${timed(Day4.solve2(Day4.input))}")
  println("  day5:")
  println(s"    ├ solution #1: ${timed(Day5.solve(Day5.input))}")
  println(s"    └ solution #2: ${timed(Day5.solve2(Day5.input))}")
  println("  day6:")
  println(s"    ├ solution #1: ${timed(Day6.solve(Day6.input))}")
  println(s"    └ solution #2: ${timed(Day6.solve2(Day6.input))}")
  println("  day7:")
  println(s"    ├ solution #1: ${timed(Day7.solve(Day7.input))}")
  println(s"    └ solution #2: ${timed(Day7.solve2(Day7.input))}")
  println("  day8:")
  println(s"    ├ solution #1: ${timed(Day8.solve(Day8.input))}")
  println(s"    └ solution #2: ${timed(Day8.solve2(Day8.input))}")
  // println("  day9:")
  // println(s"    ├ solution #1: ${timed(Day9.solve(Day9.input))}")
  // println(s"    └ solution #2: ${timed(Day9.solve2(Day9.input))}")
  // println("  day10:")
  // println(s"    ├ solution #1: ${timed(Day10.solve(Day10.input))}")
  // println(s"    └ solution #2: ${timed(Day10.solve2(Day10.input))}")
  // println("  day11:")
  // println(s"    ├ solution #1: ${timed(Day11.solve(Day11.input))}")
  // println(s"    └ solution #2: ${timed(Day11.solve2(Day11.input))}")
  // println("  day12:")
  // println(s"    ├ solution #1: ${timed(Day12.solve(Day12.input))}")
  // println(s"    └ solution #2: ${timed(Day12.solve2(Day12.input))}")
